### PR TITLE
bump/jandex

### PR DESCRIPTION
**Pull request by glefloch**
This update the jandex version used by the plugin to 2.3.0.Final

### CODE REVIEW

**Comment by aalmiray** [comment]
Thank you! FWIW the jandex version must be updated at 2 places. Here's the second one

https://github.com/kordamp/jandex-gradle-plugin/blob/master/src/main/groovy/org/kordamp/gradle/plugin/jandex/JandexPlugin.groovy#L48

**Comment by glefloch** [comment]
@aalmiray I pushed a new PR with the other update. Thanks for the hint :)

**Comment by aalmiray** [comment]
Thanks again. Release `0.11.0` coming up in a few minutes.

**Comment by aalmiray** [comment]
@gsmet release is ready https://github.com/kordamp/jandex-gradle-plugin/releases/tag/v0.11.0

**Comment by gsmet** [comment]
Cool, thanks a lot!

**Pull request merged**
